language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0

before_install: gem install bundler # update bundler.
script: "script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false

cache: bundler
sudo: false
